name: optable-pair-cli CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  GOPATH: ${{ github.workspace }}

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v3
      - name: Setup Pre-commit
        uses: pre-commit/action@v3.0.1
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: '${{ env.GOPATH }}/go.mod'
      - name: Install pre-commit hook environments
        run: pre-commit install-hooks
      - name: Run all pre-commit hooks
        run: pre-commit run --all-files
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: '${{ env.GOPATH }}/go.mod'
      - name: Install dependencies
        run: go get ./...
      - name: Build
        run: make build
